// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, ProductsReadProductsData, ProductsReadProductsResponse, ProductsCreateProductData, ProductsCreateProductResponse, ProductsReadProductData, ProductsReadProductResponse, ProductsUpdateProductData, ProductsUpdateProductResponse, ProductsDeleteProductData, ProductsDeleteProductResponse, ScrapesRunScrapeData, ScrapesRunScrapeResponse, SignalsReadSignalsData, SignalsReadSignalsResponse, SignalsCreateSignalData, SignalsCreateSignalResponse, SignalsReadSignalData, SignalsReadSignalResponse, SignalsDeleteSignalData, SignalsDeleteSignalResponse, SourcesReadSourcesData, SourcesReadSourcesResponse, SourcesCreateSourceData, SourcesCreateSourceResponse, SourcesReadSourceData, SourcesReadSourceResponse, SourcesUpdateSourceData, SourcesUpdateSourceResponse, SourcesDeleteSourceData, SourcesDeleteSourceResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse, WatchlistsReadWatchlistsData, WatchlistsReadWatchlistsResponse, WatchlistsCreateWatchlistData, WatchlistsCreateWatchlistResponse, WatchlistsReadWatchlistData, WatchlistsReadWatchlistResponse, WatchlistsUpdateWatchlistData, WatchlistsUpdateWatchlistResponse, WatchlistsDeleteWatchlistData, WatchlistsDeleteWatchlistResponse } from './types.gen';

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ProductsService {
    /**
     * Read Products
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ProductsPublic Successful Response
     * @throws ApiError
     */
    public static readProducts(data: ProductsReadProductsData = {}): CancelablePromise<ProductsReadProductsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/products/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Product
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ProductPublic Successful Response
     * @throws ApiError
     */
    public static createProduct(data: ProductsCreateProductData): CancelablePromise<ProductsCreateProductResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/products/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Product
     * @param data The data for the request.
     * @param data.id
     * @returns ProductPublic Successful Response
     * @throws ApiError
     */
    public static readProduct(data: ProductsReadProductData): CancelablePromise<ProductsReadProductResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/products/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Product
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ProductPublic Successful Response
     * @throws ApiError
     */
    public static updateProduct(data: ProductsUpdateProductData): CancelablePromise<ProductsUpdateProductResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/products/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Product
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteProduct(data: ProductsDeleteProductData): CancelablePromise<ProductsDeleteProductResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/products/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ScrapesService {
    /**
     * Run Scrape
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ScrapeRunPublic Successful Response
     * @throws ApiError
     */
    public static runScrape(data: ScrapesRunScrapeData = {}): CancelablePromise<ScrapesRunScrapeResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/scrapes/run',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class SignalsService {
    /**
     * Read Signals
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns DropSignalsPublic Successful Response
     * @throws ApiError
     */
    public static readSignals(data: SignalsReadSignalsData = {}): CancelablePromise<SignalsReadSignalsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/signals/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Signal
     * @param data The data for the request.
     * @param data.requestBody
     * @returns DropSignalPublic Successful Response
     * @throws ApiError
     */
    public static createSignal(data: SignalsCreateSignalData): CancelablePromise<SignalsCreateSignalResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/signals/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Signal
     * @param data The data for the request.
     * @param data.id
     * @returns DropSignalPublic Successful Response
     * @throws ApiError
     */
    public static readSignal(data: SignalsReadSignalData): CancelablePromise<SignalsReadSignalResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/signals/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Signal
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteSignal(data: SignalsDeleteSignalData): CancelablePromise<SignalsDeleteSignalResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/signals/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class SourcesService {
    /**
     * Read Sources
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns RetailerSourcesPublic Successful Response
     * @throws ApiError
     */
    public static readSources(data: SourcesReadSourcesData = {}): CancelablePromise<SourcesReadSourcesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sources/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Source
     * @param data The data for the request.
     * @param data.requestBody
     * @returns RetailerSourcePublic Successful Response
     * @throws ApiError
     */
    public static createSource(data: SourcesCreateSourceData): CancelablePromise<SourcesCreateSourceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/sources/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Source
     * @param data The data for the request.
     * @param data.id
     * @returns RetailerSourcePublic Successful Response
     * @throws ApiError
     */
    public static readSource(data: SourcesReadSourceData): CancelablePromise<SourcesReadSourceResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sources/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Source
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns RetailerSourcePublic Successful Response
     * @throws ApiError
     */
    public static updateSource(data: SourcesUpdateSourceData): CancelablePromise<SourcesUpdateSourceResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/sources/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Source
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteSource(data: SourcesDeleteSourceData): CancelablePromise<SourcesDeleteSourceResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/sources/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}

export class WatchlistsService {
    /**
     * Read Watchlists
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns WatchlistsPublic Successful Response
     * @throws ApiError
     */
    public static readWatchlists(data: WatchlistsReadWatchlistsData = {}): CancelablePromise<WatchlistsReadWatchlistsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/watchlists/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Watchlist
     * @param data The data for the request.
     * @param data.requestBody
     * @returns WatchlistPublic Successful Response
     * @throws ApiError
     */
    public static createWatchlist(data: WatchlistsCreateWatchlistData): CancelablePromise<WatchlistsCreateWatchlistResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/watchlists/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Watchlist
     * @param data The data for the request.
     * @param data.id
     * @returns WatchlistPublic Successful Response
     * @throws ApiError
     */
    public static readWatchlist(data: WatchlistsReadWatchlistData): CancelablePromise<WatchlistsReadWatchlistResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/watchlists/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Watchlist
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns WatchlistPublic Successful Response
     * @throws ApiError
     */
    public static updateWatchlist(data: WatchlistsUpdateWatchlistData): CancelablePromise<WatchlistsUpdateWatchlistResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/watchlists/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Watchlist
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteWatchlist(data: WatchlistsDeleteWatchlistData): CancelablePromise<WatchlistsDeleteWatchlistResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/watchlists/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}