// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DropSignalCreate = {
    product_id: string;
    source_id?: (string | null);
    observed_price: number;
    stock_status: string;
    source_type?: string;
    url?: (string | null);
    observed_at?: string;
};

export type DropSignalPublic = {
    product_id: string;
    source_id?: (string | null);
    observed_price: number;
    stock_status: string;
    source_type?: string;
    url?: (string | null);
    observed_at?: string;
    id: string;
    created_at?: (string | null);
};

export type DropSignalsPublic = {
    data: Array<DropSignalPublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProductCreate = {
    game: string;
    name: string;
    product_type: string;
    msrp: number;
    image_url?: (string | null);
};

export type ProductPublic = {
    game: string;
    name: string;
    product_type: string;
    msrp: number;
    image_url?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type ProductsPublic = {
    data: Array<ProductPublic>;
    count: number;
};

export type ProductUpdate = {
    game?: (string | null);
    name?: (string | null);
    product_type?: (string | null);
    msrp?: (number | null);
    image_url?: (string | null);
};

export type RetailerSourceCreate = {
    product_id: string;
    retailer_name: string;
    url: string;
    price_selector?: (string | null);
    stock_selector?: (string | null);
    is_active?: boolean;
};

export type RetailerSourcePublic = {
    product_id: string;
    retailer_name: string;
    url: string;
    price_selector?: (string | null);
    stock_selector?: (string | null);
    is_active?: boolean;
    id: string;
    created_at?: (string | null);
};

export type RetailerSourcesPublic = {
    data: Array<RetailerSourcePublic>;
    count: number;
};

export type RetailerSourceUpdate = {
    product_id?: (string | null);
    retailer_name?: (string | null);
    url?: (string | null);
    price_selector?: (string | null);
    stock_selector?: (string | null);
    is_active?: (boolean | null);
};

export type ScrapeRunPublic = {
    message: string;
    source_id?: (string | null);
};

export type ScrapeRunRequest = {
    source_id?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WatchlistCreate = {
    product_id: string;
    msrp_margin_percent?: number;
    max_price?: (number | null);
    email_enabled?: boolean;
};

export type WatchlistPublic = {
    product_id: string;
    msrp_margin_percent?: number;
    max_price?: (number | null);
    email_enabled?: boolean;
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type WatchlistsPublic = {
    data: Array<WatchlistPublic>;
    count: number;
};

export type WatchlistUpdate = {
    product_id?: (string | null);
    msrp_margin_percent?: (number | null);
    max_price?: (number | null);
    email_enabled?: (boolean | null);
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProductsReadProductsData = {
    limit?: number;
    skip?: number;
};

export type ProductsReadProductsResponse = (ProductsPublic);

export type ProductsCreateProductData = {
    requestBody: ProductCreate;
};

export type ProductsCreateProductResponse = (ProductPublic);

export type ProductsReadProductData = {
    id: string;
};

export type ProductsReadProductResponse = (ProductPublic);

export type ProductsUpdateProductData = {
    id: string;
    requestBody: ProductUpdate;
};

export type ProductsUpdateProductResponse = (ProductPublic);

export type ProductsDeleteProductData = {
    id: string;
};

export type ProductsDeleteProductResponse = (Message);

export type ScrapesRunScrapeData = {
    requestBody?: (ScrapeRunRequest | null);
};

export type ScrapesRunScrapeResponse = (ScrapeRunPublic);

export type SignalsReadSignalsData = {
    limit?: number;
    skip?: number;
};

export type SignalsReadSignalsResponse = (DropSignalsPublic);

export type SignalsCreateSignalData = {
    requestBody: DropSignalCreate;
};

export type SignalsCreateSignalResponse = (DropSignalPublic);

export type SignalsReadSignalData = {
    id: string;
};

export type SignalsReadSignalResponse = (DropSignalPublic);

export type SignalsDeleteSignalData = {
    id: string;
};

export type SignalsDeleteSignalResponse = (Message);

export type SourcesReadSourcesData = {
    limit?: number;
    skip?: number;
};

export type SourcesReadSourcesResponse = (RetailerSourcesPublic);

export type SourcesCreateSourceData = {
    requestBody: RetailerSourceCreate;
};

export type SourcesCreateSourceResponse = (RetailerSourcePublic);

export type SourcesReadSourceData = {
    id: string;
};

export type SourcesReadSourceResponse = (RetailerSourcePublic);

export type SourcesUpdateSourceData = {
    id: string;
    requestBody: RetailerSourceUpdate;
};

export type SourcesUpdateSourceResponse = (RetailerSourcePublic);

export type SourcesDeleteSourceData = {
    id: string;
};

export type SourcesDeleteSourceResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WatchlistsReadWatchlistsData = {
    limit?: number;
    skip?: number;
};

export type WatchlistsReadWatchlistsResponse = (WatchlistsPublic);

export type WatchlistsCreateWatchlistData = {
    requestBody: WatchlistCreate;
};

export type WatchlistsCreateWatchlistResponse = (WatchlistPublic);

export type WatchlistsReadWatchlistData = {
    id: string;
};

export type WatchlistsReadWatchlistResponse = (WatchlistPublic);

export type WatchlistsUpdateWatchlistData = {
    id: string;
    requestBody: WatchlistUpdate;
};

export type WatchlistsUpdateWatchlistResponse = (WatchlistPublic);

export type WatchlistsDeleteWatchlistData = {
    id: string;
};

export type WatchlistsDeleteWatchlistResponse = (Message);